# Generated by Django 2.2.4 on 2021-08-05 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='href',
            field=models.TextField(default=''),
        ),
    ]
